"use client";
import { useState } from "react";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db } from "../lib/firebase";
import { guestId } from "../lib/guest";
const lessons = [
 { title:"Argument Structure", subtitle:"Claim · Evidence · Warrant · Impact", content:<><p>A strong argument does more than state an opinion. It walks a judge from a clear claim to a reason the claim matters.</p><h3>Claim</h3><p>State the point you want the judge to accept. Keep it specific and debatable.</p><h3>Evidence</h3><p>Offer a credible fact, example, study, or piece of reasoning that supports the claim.</p><h3>Warrant</h3><p>Explain the bridge: why does this evidence prove your claim? Never assume that connection is obvious.</p><h3>Impact</h3><p>Show why the argument matters. Who is affected, how much, and why should it influence the round?</p></>},
 { title:"Building Rebuttals", subtitle:"Answer the argument, not just the speaker", content:<><p>A rebuttal is a direct response to an opponent’s reasoning. Name their claim, then tell the judge exactly where it breaks.</p><h3>Three useful moves</h3><ul><li><b>Turn:</b> their argument actually supports your side.</li><li><b>Take-out:</b> their evidence or logic is unreliable.</li><li><b>Weigh:</b> even if true, it matters less than your impact.</li></ul><p>Use clear signposts such as “Their second contention fails because…” so the judge can follow the clash.</p></>},
 { title:"Delivery Basics", subtitle:"Clarity beats performance", content:<><p>Good delivery helps a judge hear your reasoning. Aim for a pace that leaves room for important ideas to land.</p><h3>Try this</h3><ul><li>Pause briefly after a claim and before an impact.</li><li>Stress the key noun or verb, not every word.</li><li>Replace filler words with a quiet breath.</li><li>Practice a little slower than feels natural.</li></ul></>},
 { title:"Handling Cross-Examination", subtitle:"Questions with a purpose", content:<><p>Cross-examination is not a quiz; it is a chance to expose a gap and set up your next speech.</p><h3>Ask targeted questions</h3><p>Seek definitions, missing links, evidence sources, and assumptions. Keep questions short, listen carefully, and ask a follow-up when an answer reveals a weakness.</p><p>When answering, be direct. If you do not know, acknowledge the limit and return to what your argument does establish.</p></>}
];
export default function LessonsPage(){
 console.log("LESSONS PAGE VERSION 999 - completionState should start idle");
 const [chosen,setChosen]=useState(0); const [completionState,setCompletionState]=useState<"idle"|"saving"|"completed"|"error">("idle"); const lesson=lessons[chosen]; const saving=completionState==="saving"; const done=completionState==="completed"; async function complete(){setCompletionState("saving");try{await addDoc(collection(db,"guests",guestId(),"lessonCompletions"),{lesson:lesson.title,completedAt:serverTimestamp()});console.log("Lesson completion saved:",lesson.title);setCompletionState("completed")}catch(error){console.error("Failed to save lesson completion:",error);setCompletionState("error")}} return <main className="page-wrap"><div className="page-intro"><h1 className="page-title">Learning Path</h1><p className="subtle">Master the art of persuasion through structured modules.</p></div><div className="page-grid"><div className="lesson-list">{lessons.map((item,index)=><button className={chosen===index?"active":""} onClick={()=>{setChosen(index);setCompletionState("idle")}} key={item.title}><b>{item.title}</b><small>{item.subtitle}</small></button>)}</div><article className="panel lesson-content"><div className="eyebrow">LESSON {chosen+1} OF {lessons.length}</div><h2>{lesson.title}</h2>{lesson.content}<div className="complete-row"><button onClick={complete} disabled={saving||done} className="button button-secondary">{saving?"Saving…":done?"Completed ✓":"Mark complete"}</button>{done&&<span className="status">Saved to your progress</span>}{completionState==="error"&&<span className="status">We couldn’t save that completion. Please try again.</span>}</div></article></div></main>
}